groups = [
	{ name = "Main Mods", mods = [
		"create-fabric",
		"enchantedshulkers",
		"enderchests-fabric",
		"oh-the-biomes-youll-go-fabric",
		"roughly-enough-items",
	] },
	{ name = "Optimization - Misc", mods = [
		"c2me-fabric",
		"chunky",
		"cull-less-leaves",
		"dynamic-fps",
		"entity-collision-fps-fix",
		"fastanim",
		"ferrite-core",
		"forgetmechunk",
		"indium",
		"krypton",
		"lazydfu",
		"lithium",
		"lmd",
		"recipe-cache",
		"thorium",
	] },
	{ name = "Optimization - Rendering", mods = [
		"better-beds",
		"better-biome-blend",
		"entity-view-distance",
		"entityculling",
		"moreculling",
		"sodium",
		"sodium-extra",
	] },
	{ name = "Optimization - Redstone", mods = [
		"alternate-current",
	] },
	{ name = "Optimization - Lighting", mods = [
		"starlight",
	] },
	{ name = "Optimization - Networking", mods = [
		"badpackets",
		"connectivity",
		"fabricproxy-lite",
		"xl-packets-fabric",
	] },
	{ name = "Keybinds and Config Mods", mods = [
		"amecs",
		"default-options-fabric",
		"modmenu",
		"rebind-all-the-keys",
		"reeses-sodium-options",
		"remember-my-txt",
		"screenshot-to-clipboard",
		"smooth-scrolling-everywhere-fabric",
		"tipthescales",
		"too-many-binds",
		"vtdownloader",
	] },
	{ name = "Decoration Mods", mods = [
		"armor-statues",
		"bedspreads-fabric",
		"consistencyplus",
		"dark-paintings",
		"decorative-blocks",
		"dramatic-doors",
		"enchanted-vertical-slabs",
		"lanterns-bow",
		"macaws-bridges",
		"macaws-doors",
		"macaws-fences-and-walls",
		"macaws-paths-and-pavings",
		"mo-glass",
		"modern-glass-doors",
		"more-music-discs",
		"naturalist",
		"shards",
		"supplementaries",
	] },
	{ name = "OptiFine Replacement", mods = [
		"cit-resewn",
		"continuity",
		"entitytexturefeatures",
		"iris",
		"lambdynamiclights",
		"sodium-shadowy-path-blocks",
		"unofficial-sodium-biome-blending-fix",
	] },
	{ name = "Utility Mods", mods = [
		"accurate-block-placement",
		"adaptive-tooltips",
		"advanced-tooltips",
		"appleskin",
		"auto-clicker-fabric",
		"beenfo",
		"better-third-person",
		"betterdarkmode",
		"BetterF3",
		"blockmeter",
		"bobby",
		"borderless-mining",
		"brb",
		"chat-up",
		"chest-tracker",
		"client-tweaks-fabric",
		"couplings",
		"dark-mode-everywhere-fabric",
		"deathlog",
		"discontinuous-beacon-beams",
		"easiervillagertrading",
		"emotecraft",
		"held-item-info",
		"horsestatsvanilla",
		"hotbarcycle",
		"inventory-essentials",
		"inventory-profiles-next",
		"leaves-be-gone",
		"litematica",
		"minihud",
		"morechathistory",
		"organized-tabs",
		"pick-block-pro",
		"sheep-consistency",
		"shift-scroll-fix",
		"shulkerboxtooltip",
		"skinswapper",
		"statuseffecttimer",
		"text-utilities",
		"the-one-probe-fabric",
		"tool-stats",
		"trinkets",
		"tweakeroo",
		"worldeditcui-fabric",
		"xaeros-minimap",
		"xaeros-world-map",
		"zoomify",
	] },
	{ name = "Chat and Discord", mods = [
		"chat-heads",
		"chat-signing-hider",
		"chattix",
		"simple-discord-link-bot-forge-fabric-spigot",
		"simple-voice-chat",
	] },
	{ name = "Player List", mods = [
		"afkdisplay",
		"better-ping-display-fabric",
		"orderedplayerlist",
		"player-pronouns",
		"styled-nicknames",
		"styledplayerlist",
	] },
	{ name = "Maps and Minimaps", mods = [
		"dynmapforge",
		"opac-fabric-create-support",
		"open-parties-and-claims",
	] },
	{ name = "Storage", mods = [
		"expanded-enderchest",
		"expanded-storage",
		"gravestones",
		"invview",
	] },
	{ name = "Server QoL", mods = [
		"armored-elytra",
		"attributefix",
		"audioplayer",
		"axes-are-weapons",
		"charm-of-undying-fabric",
		"creative-one-punch",
		"crops-love-rain",
		"cycle-paintings",
		"deepslatecutting",
		"expanded-axe-enchanting",
		"headindex",
		"image2map",
		"inventory-totem",
		"keepheadnames",
		"lapis-reserve",
		"litematica-server-paster",
		"login-protection",
		"netherportalfix-fabric",
		"no-sneaking-over-magma",
		"rightclickharvest",
		"server-hats",
		"servertick",
		"sleep-warp",
		"stack-refill-fabric",
		"suggestion-tweaker",
		"superflat-world-no-slimes",
		"worldedit",
	] },
	{ name = "Server Management", mods = [
		"anti-xray",
		"banhammer",
		"commandaliases",
		"coord-finder",
		"essential-commands",
		"fabric-votifier",
		"fastback",
		"ledger",
		"ledger-databases",
		"luckperms-fabric-placeholderapi-hook",
		"mysql-jdbc",
		"placeholder-api",
		"rules",
		"servercore",
		"set-world-spawn-point",
		"vanilla-permissions",
		"vote-command",
	] },
	{ name = "Libraries", mods = [
		"architectury-api",
		"arrp",
		"balm",
		"balm-fabric",
		"bookshelf",
		"celib",
		"cloth-api",
		"cloth-config",
		"collective",
		"fabric-api",
		"fabric-language-kotlin",
		"forge-config-api-port",
		"forge-config-api-port-fabric",
		"geckolib",
		"ingredient-extension-api",
		"jamlib",
		"koroworld-lib",
		"libipn",
		"luckperms",
		"malilib",
		"moonlight-lib",
		"puzzles-lib",
		"respro",
		"rhino",
		"shetiphiancore-fabric",
		"TerraBlender-fabric",
		"yacl",
	] },
	{ name = "Compatibility Mods", mods = [
		"every-compat",
		"kleeslabs-fabric",
		"refabricated-slabs",
		"vertical-slabs-compat",
	] },
	{ name = "Debugging", mods = [
		"advancements-debug",
		"auth-me",
		"better-tips",
		"crafty-crashes",
		"kubejs",
		"mixin-conflict-helper",
		"mixintrace",
		"observable",
		"ponder",
		"probejs",
		"spark",
	] },
	{ name = "Bug Fixes / Many Feature", mods = [
		"blanket",
		"carpet",
		"carpet-fixes",
		"fabrication",
	] },
	{ name = "Unknown", mods = [
		"better-advancements",
		"crossstitch",
		"death-knell",
		"enchantment-lore",
		"interdimensional-map-markers",
	] },
]
