[[groups]]
name = "Main Mods"
mods = [
	"create-fabric",
	"enchantedshulkers",
	"enderchests-fabric",
	"inventorytotem-fabric",
	"oh-the-biomes-youll-go-fabric",
	"roughly-enough-items",
	"simplevoicechat-fabric",
]

[[groups]]
name = "Optimization Mods"
mods = [
	"alternate-current",
	"badpackets-fabric",
	"betterbeds",
	"c2me-fabric",
	"cachemyenderchest",
	"chunky",
	"cull-less-leaves",
	"dynamic-fps",
	"entityculling-fabric",
	"Fastload",
	"ferritecore",
	"forgetmechunk",
	"indium",
	"iris",
	"krypton",
	"lazydfu",
	"lithium-fabric",
	"memoryleakfix",
	"moreculling",
	"smoothboot-fabric",
	"sodium-extra",
	"sodium-fabric",
	"spark",
	"starlight",
	"tabtps-fabric",
	"thorium",
]

[[groups]]
name = "Decoration Mods"
mods = [
	"ArmorStatues"
]

[[groups]]
name = "Utility Mods"
mods = [
	"accurate-block-placement",
	"advancedtooltips",
	"appleskin-fabric",
	"auto-clicker-fabric",
	"beenfo",
	"better-dark-mode",
	"BetterAdvancements-Fabric",
	"BetterF3",
	"better-third-person",
	"blockmeter",
	"bobby",
	"borderless-mining",
	"brb",
	"chat-up",
	"cyclepaintings-fabric",
	"easiervillagertrading",
	"horse-stats-vanilla",
	"hotbarcycle",
	"inventory-profiles-next",
	"litematica-fabric",
	"macos-input-fixes",
	"minihud-fabric",
	"mixintrace",
	"modmenu",
	"morechathistory",
	"notenoughcrashes",
	"observable",
	"rebind-all-the-keys",
	"reeses_sodium_options",
	"screenshot-to-clipboard",
	"sheep-consistency",
	"shift-scroll-fix",
	"shulkerboxtooltip-fabric",
	"skin-swapper-fabric",
	"statuseffecttimer",
	"text-utilities-fabric",
	"the-one-probe-fabric",
	"ToolStats",
	"tooltipfix",
	"tweakeroo-fabric",
	"vt-downloader",
	"whereisit",
	"worldedit-mod",
	"worldeditcui-fabric",
	"xaeros-minimap",
	"xaeros-world-map",
	"Zoomify",
	"inventory-essentials",
	"couplings",
	"snowyleavesplus",
	"leaves-be-gone",
]

[[groups]]
name = "OptiFine Replacement"
mods = [
	"CITResewn",
	"continuity",
	"entity_texture_features_fabric",
	"lambdynamiclights",
	"sodium-shadowy-path-blocks",
]

[[groups]]
name = "Libraries"
mods = [
	"balm",
	"architectury",
	"Bookshelf-Fabric",
	"collective-fabric",
	"Controlling-fabric",
	"fabric-api",
	"fabric-language-kotlin",
	"libIPN-fabric",
	"malilib-fabric",
	"owo-lib",
	"PuzzlesLib",
	"shetiphiancore-fabric",
	"TerraBlender-fabric",
	"YetAnotherConfigLib",
	"placeholder-api-fabric",
	"luckperms",
	"luckperms-fabric-placeholdersapi-hook",
]

[[groups]]
name = "Server Management"
mods = [
	"restart-server",
	"vanilla-permissions",
	"coord-finder",
	"rules",
	"login-protection",
	"mcdiscordchat",
]
