name = "CraftersMC Modpack"
author = "chaws"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9507ef0eb3744ac8b7be37ddf4a62f1a977505bbe8c9dfe47fdb562c03c2e1f9"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"

[options]
acceptable-game-versions = ["1.19", "1.19.0"]
