name = "CraftersMC Modpack"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75ac0ed2cff6f34ac07115be627c4c64ef79c3b0de7de4051265128bed927be3"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
