name = "CraftersMC Modpack"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1798fe76095a2ab014e6554530ca8aa480330ac307b29cf015977122cd5bf0ed"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
