name = "CraftersMC Modpack"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16d82162ab910485d69c9fb5bd8ca087ad90d4348845e8dbf291121cda4b3d79"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
