name = "CraftersMC Modpack"
author = "chaws"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e08613392c9df3cd6e1c0a4958f8c3572a650350d04c975af759c2feade1aff0"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"

[options]
acceptable-game-versions = ["1.18.2", "1.19.0"]
