name = "CraftersMC Modpack"
author = "chaws"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4002ed868295e56bed40c58f54e0f5da44b34d8238e00a8230656e5ae80a48a4"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"

[options]
acceptable-game-versions = ["1.19.0"]
