name = "craftersmc"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "394c0efb6e5ce512bee9fcca5d917692b44219bb2d55c8ca7271c66a3878cb0d"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
