name = "craftersmc"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07641a26f89676484afd540471440723965ea786c7d02421bc843637c24ff6a7"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
