name = "CraftersMC Modpack"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cfab09101ee044ed3ccbf4658632b0dc447e288cbd368d003e45069dddb5897"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
