name = "CraftersMC Modpack"
author = "chaws"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b68be95157ea04693245ab651758aa6fe1dd3b55fc9daed9008c11987e5acb9"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"

[options]
acceptable-game-versions = ["1.19", "1.19.0"]
