name = "CraftersMC Modpack"
author = "chaws"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "181ddf2c710a6e5d7d4a9dc1caba2d9d4b0000b75180a2e1b089c5afe23c8e3d"

[versions]
minecraft = "1.19"
quilt = "0.17.2-beta.2"

[options]
acceptable-game-versions = ["1.19", "1.19.0"]
