name = "CraftersMC Modpack"
author = "chaws"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66c76e80dea392707328b031658f4c70a69b315a6bae9020636b3073e5771bf4"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"

[options]
acceptable-game-versions = ["1.19.0"]
