name = "CraftersMC Modpack"
author = "chaws"
version = "1.19.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "887ceaf9cafa1fd0cd0749fe867bd04e2b7ecc63b2f79d187864b3b7b2807193"

[versions]
minecraft = "1.19"
quilt = "0.17.1-beta.1"

[options]
acceptable-game-versions = ["1.19", "1.19.0"]
