# yaml-language-server: $schema=../../.schemas/command-alias.schema.json
# schemaVersion: 1
# commandMode: COMMAND_CUSTOM
# command: tpsbar
# actions:
#   - command: tabtps toggle bossbar
#     commandType: CLIENT
