minimalLabelSize = true
deleteBoxesOnDisable = true
sendBoxes = true
showBoxesWhenDisabled = false
backgroundForLabels = true
incrementColor = true
innerDiagonal = true
showOtherUsersBoxes = false
colorIndex = 0
