enableSodiumMenu = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 48.0
leavesCullingMode = "DEFAULT"
leavesCullingDepth = 2
