enableSodiumMenu = true
# https://github.com/Fabricators-of-Create/Create/issues/649
useBlockStateCulling = false
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingDepth = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
byg = true
milk = true
create = true
enderchests = true
minecraft = true
