enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
mcwfences = true
mcwdoors = true
everycomp = true
v_slab_compat = true
consistency_plus = true
expandedstorage = true
supplementaries = true
mo_glass = true
enchanted-vertical-slabs = true
mcwbridges = true
byg = true
bedspreads = true
milk = true
create = true
decorative_blocks = true
refabslab = true
dramaticdoors = true
enderchests = true
mcwpaths = true
naturalist = true
minecraft = true
glassdoor = true
gravestones = true
