name = "Accurate Block Placement"
filename = "accurate-block-placement-1.0.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3673/256/accurate-block-placement-1.0.12.jar"
hash-format = "sha1"
hash = "ab08b5ef84c509ef66b941cf1d5be4a43baee5a8"

[update]
[update.curseforge]
file-id = 3673256
project-id = 323316
