name = "Alternate Current"
filename = "alternate-current-mc1.18-1.1.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/r0v8vy1s/versions/mc1.18-1.1.0/alternate-current-mc1.18-1.1.0.jar"
hash-format = "sha1"
hash = "d6b1036e76c82186c3925c4258f4d7d1ee873de8"

[update]
[update.modrinth]
mod-id = "r0v8vy1s"
version = "9F6atBKt"
