name = "Boat Container"
filename = "boatcontainer-1.0.4-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3783/209/boatcontainer-1.0.4-1.18.2.jar"
hash-format = "sha1"
hash = "06cc373f1b4c00b5d38e444e6c34b17ef7003432"

[update]
[update.curseforge]
file-id = 3783209
project-id = 526274
