name = "Bookshelf"
filename = "Bookshelf-Fabric-1.18.2-13.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3741/97/Bookshelf-Fabric-1.18.2-13.0.11.jar"
hash-format = "sha1"
hash = "1ea9ff35ff11c409e034220c3adcd4b6b05c7dfc"

[update]
[update.curseforge]
file-id = 3741097
project-id = 228525
