name = "Connected Doors"
filename = "connected-doors-1.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/417/connected-doors-1.1+1.18.jar"
hash-format = "sha1"
hash = "36c08827495e842c0ab46ddb0fcda127dce5cd45"

[update]
[update.curseforge]
file-id = 3542417
project-id = 498248
