name = "Consistency+"
filename = "consistency_plus-0.5.0-RC3+1.18.2-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/nDHcEOt3/versions/0.5.0-RC3+Fabric-1.18.2/consistency_plus-0.5.0-RC3%2B1.18.2-fabric.jar"
hash-format = "sha1"
hash = "d533332ce6540eeb1073179241182fdd8d7d4d36"

[update]
[update.modrinth]
mod-id = "nDHcEOt3"
version = "tXpeXwZ6"
