name = "Entity Texture Features [Fabric]"
filename = "entity-texture-features-3.0.1-mc1.18.x.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/3.0.1/entity-texture-features-3.0.1-mc1.18.x.jar"
hash-format = "sha1"
hash = "c6a272e4c0f2b8777589cddf8298bbec79db341c"
mode = ""

[update]
[update.modrinth]
mod-id = "BVzZfTc1"
version = "OyYm6CF5"
