name = "Entity Texture Features [Fabric]"
filename = "entity-texture-features-3.0.0-mc1.18.x.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/3.0.0/entity-texture-features-3.0.0-mc1.18.x.jar"
hash-format = "sha1"
hash = "ccb1bb691229a1204799da5c8e2e59ba23ea0509"

[update]
[update.modrinth]
mod-id = "BVzZfTc1"
version = "nYzDnjGu"
