name = "Entity Texture Features [Fabric]"
filename = "entity-texture-features-1.18+_2.6.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/2.6.0/entity-texture-features-1.18%2B_2.6.0.jar"
hash-format = "sha1"
hash = "f2143a3818a3918e6e3ec74b5aa0276215866af3"

[update]
[update.modrinth]
mod-id = "BVzZfTc1"
version = "uqLRu1PW"
