name = "Entity Texture Features [Fabric]"
filename = "entity-texture-features-3.0.2-mc1.18.x.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/BVzZfTc1/versions/3.0.2/entity-texture-features-3.0.2-mc1.18.x.jar"
hash-format = "sha1"
hash = "ec0ff0fde9748798e05ce4d420d4033916966f0e"
mode = ""

[update]
[update.modrinth]
mod-id = "BVzZfTc1"
version = "d9gMEg0u"
