name = "Entity View Distance"
filename = "entity-view-distance-1.0.1+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ihnBJ6on/versions/1.0.1+1.18.2/entity-view-distance-1.0.1%2B1.18.2.jar"
hash-format = "sha1"
hash = "d6b403a145ac58f9849838c45e326469cdd204f5"

[update]
[update.modrinth]
mod-id = "ihnBJ6on"
version = "H5wEoQuA"
