name = "Fabric API"
filename = "fabric-api-0.54.0+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "bb41e2af744336c3c2c94a723fa7d73e37099aa0"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3811649
project-id = 306612
