name = "Fabric Votifier"
filename = "fabric-votifier-1.1.3.jar"
side = "server"

[download]
url = "https://modpack.craftersmc.com/mods/fabric-votifier-1.1.3.jar"
hash-format = "sha1"
hash = "cfafe8800c823faf700d1edd4ee088022b707365"
