name = "Fabric Restart"
filename = "fabric-restart-1.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3745/953/fabric-restart-1.5.3.jar"
hash-format = "sha1"
hash = "56729898799a461f2fc64c1aecce5f3be9ee0b86"

[update]
[update.curseforge]
file-id = 3745953
project-id = 482945
