name = "Plasmo Voice"
filename = "plasmovoice-fabric-1.18-1.2.12.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/1bZhdhsH/versions/fabric-1.18-1.2.12/plasmovoice-fabric-1.18-1.2.12.jar"
hash-format = "sha1"
hash = "0c03c3cb32c9da5e6bad247e7579616ecf685680"

[update]
[update.modrinth]
mod-id = "1bZhdhsH"
version = "DgR7LRrJ"
