name = "Servux"
filename = "servux-fabric-1.18.2-0.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/439/servux-fabric-1.18.2-0.1.0.jar"
hash-format = "sha1"
hash = "07d64bc727dc4e7bf963f99572f4a0a0caaaf0a1"

[update]
[update.curseforge]
file-id = 3671439
project-id = 406323
