name = "Server Translations"
filename = "Server-Translations-1.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3045/345/Server-Translations-1.3.3.jar"
hash-format = "sha1"
hash = "9a419d3c6edfdf25c11b894e5763ebded26c1145"

[update]
[update.curseforge]
file-id = 3045345
project-id = 400548
