name = "squaremap"
filename = "squaremap-fabric-mc1.18.2-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3782/363/squaremap-fabric-mc1.18.2-1.1.3.jar"
hash-format = "sha1"
hash = "f275d6e1be1d3ac85ed5c36c2298dd3c881f9a57"

[update]
[update.curseforge]
file-id = 3782363
project-id = 579715
