name = "Stack Refill (Fabric)"
filename = "stackrefill-fabric_1.18.x-2.1.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3650/148/stackrefill-fabric_1.18.x-2.1.jar"
hash-format = "sha1"
hash = "59a1491948237e9a7d26aa07856e91ecc90cec7e"

[update]
[update.curseforge]
file-id = 3650148
project-id = 580682
