name = "Styled Player List"
filename = "styledplayerlist-2.1.3+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3537/721/styledplayerlist-2.1.3+1.18.jar"
hash-format = "sha1"
hash = "c5b64a69b0dd69638d2247e09c0967b086c6b2c7"

[update]
[update.curseforge]
file-id = 3537721
project-id = 442282
