name = "Too Fast"
filename = "toofast-0.0.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/624/toofast-0.0.2.3.jar"
hash-format = "sha1"
hash = "8224bd3d5f6c89407269ed9605b4183670b1c898"

[update]
[update.curseforge]
file-id = 3672624
project-id = 550678
