name = "Xaero's World Map"
filename = "XaerosWorldMap_1.22.0_Fabric_1.18.2.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3796/748/XaerosWorldMap_1.22.0_Fabric_1.18.2.jar"
hash-format = "sha1"
hash = "d6f7ff3830a3169a3e0d33045fed060b219af4b2"

[update]
[update.curseforge]
file-id = 3796748
project-id = 317780
