name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.8.2_Fabric_1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "505a6552b16ea674c6867808f78dee89d23302c4"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3798916
project-id = 263420
